name: build

on:
  workflow_run:
    workflows:
      - android-native  
      - ios-native      
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build:
    runs-on: macos-latest
    name: build
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
 
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
        
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
         
      - name: Download Android x86 Artifact
        uses: actions/download-artifact@v3
        with:
          name: pjsip-android-x86
          path: ./artifacts/android-x86
      
      - name: Download Android x86_64 Artifact
        uses: actions/download-artifact@v3
        with:
          name: pjsip-android-x86_64
          path: ./artifacts/android-x86_64
          
      - name: Download Android arm Artifact
        uses: actions/download-artifact@v3
        with:
          name: pjsip-android-armeabi-v7a
          path: ./artifacts/android-armeabi-v7a
      
      - name: Download Android arm64 Artifact
        uses: actions/download-artifact@v3
        with:
          name: pjsip-android-arm64-v8a
          path: ./artifacts/android-arm64-v8a
  
      - name: Download Android java Artifact
        uses: actions/download-artifact@v3
        with:
          name: java
          path: ./artifacts/java
      
      - name: Download Android csharp Artifact
        uses: actions/download-artifact@v3
        with:
          name: csharp
          path: ./artifacts/android/csharp
      
      - name: Download ios Artifacts
        uses: actions/download-artifact@v3
        with:
          name: pjsip-x86_64
          path: ./artifacts/ios/pjsip-x86_64
      
      - name: Download ios arm64 Artifact
        uses: actions/download-artifact@v3
        with:
          name: pjsip-arm64
          path: ./artifacts/ios/pjsip-arm64
  
      - name: Prepare Dirs
        run: |
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/org/pjsip
          mkdir -p ${{ github.workspace }}/src/libpjsua2.maui.android/pjsua2
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/lib/x86
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/lib/x86_64
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/lib/armeabi-v7a
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/lib/arm64-v8a
          mkdir -p ${{ github.workspace }}/src/libpjsua2.maui.ios/pjsua2
          mkdir -p ${{ github.workspace }}/src/libpjsua2.a/lib/arm64
          mkdir -p ${{ github.workspace }}/src/libpjsua2.a/lib/x86_64
          mv ${{ github.workspace }}/artifacts/java/java/org/pjsip/*.java ${{ github.workspace }}/src/libpjsua2.so/org/pjsip/
          mv ${{ github.workspace }}/artifacts/csharp/pjsua2/*.cs ${{ github.workspace }}/src/libpjsua2.maui.android/pjsua2
          mv ${{ github.workspace }}/artifacts/android-x86/* ${{ github.workspace }}/src/libpjsua2.so/lib/x86
          mv ${{ github.workspace }}/artifacts/android-x86_64/* ${{ github.workspace }}/src/libpjsua2.so/lib/x86_64
          mv ${{ github.workspace }}/artifacts/android-armeabi-v7a/* ${{ github.workspace }}/src/libpjsua2.so/lib/armeabi-v7a
          mv ${{ github.workspace }}/artifacts/android-arm64-v8a/* ${{ github.workspace }}/src/libpjsua2.so/lib/arm64-v8a
          mv ${{ github.workspace }}/artifacts/ios/pjsip-x86_64/lib/* ${{ github.workspace }}/src/libpjsua2.a/lib/x86_64
          mv ${{ github.workspace }}/artifacts/ios/pjsip-arm64/lib/* ${{ github.workspace }}/src/libpjsua2.a/lib/arm_64
          mv ${{ github.workspace }}/artifacts/ios/pjsip-arm64/cs/*.cs ${{ github.workspace }}/src/libpjsua2.maui.ios/pjsua2
          cd  ${{ github.workspace }}/src/libpjsua2.a/lib/x86_64
          libtool -static -o libpjsua2.a libbcg729.a libcrypto.a libssl.a libopenh264.a libopus.a libpjsua2.a
          rm -rf libbcg729.a libcrypto.a libssl.a libopenh264.a libopus.a
          cd ${{ github.workspace }}/src/libpjsua2.a/lib/arm_64
          libtool -static -o libpjsua2.a libbcg729.a libcrypto.a libssl.a libopenh264.a libopus.a libpjsua2.a
          rm -rf libbcg729.a libcrypto.a libssl.a libopenh264.a libopus.a
          
      - name: Restore Dependencies
        run: | 
          dotnet restore src/libpjsua2.maui.android/libpjsua2.maui.android.csproj
          dotnet restore src/libpjsua2.maui.ios/libpjsua2.maui.ios.csproj

      - name: Build MAUI Android
        run: dotnet publish src/libpjsua2.maui.android/libpjsua2.maui.android.csproj -c Release -f net9.0-android --no-restore
       
      - name: Build MAUI iOS
        run: dotnet publish src/libpjsua2.maui.ios/libpjsua2.maui.ios.csproj -c Release -f net9.0-ios --no-restore
     
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
      - name: Pack
        run: nuget pack src/libpjsua2maui.nuspec -version "${VERSION}"
      
      - name: Push to nuget
        run: dotnet nuget push libpjsua2maui.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${API_KEY} --skip-duplicate
        env:
          API_KEY: ${{ secrets.API_KEY }}