on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
  pull_request:
    types: [opened, synchronize, reopened]  
    
  workflow_dispatch:
  
permissions:
  contents: read

env:
    BCG729_PATH:  ${{ github.workspace }}/lib/bcg729
    OPENH264_PATH: ${{ github.workspace }}/lib/openh264
    OPENSSL_PATH: ${{ github.workspace }}/lib/openssl
    OPUS_PATH: ${{ github.workspace }}/lib/opus
    PJSIP_PATH: ${{ github.workspace }}/lib/pjsip


jobs:
  openh264:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: macos-latest
    name: Build OpenH264 
    permissions:
      contents: write
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
         submodules: 'true'
         
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
         
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install deps
      run: |

      shell: zsh
         
    - name: Build For all archs
      run: |
        cd ${{ env.OPENH264_PATH }}
        h264_makefile="Makefile"
        h264_makefile_bak="Makefile.bak"
        h264_prefix="${{ env.OPENH264_PATH }}/builds/${{ matrix.arch }}"
        h264_log="${h264_prefix}/build.log"
        mkdir -p "${h264_prefix}/logs"

        pushd . > /dev/null
  
        echo "Building h264 for ${{ matrix.arch }}"

        cp "${h264_makefile}" "${h264_makefile_bak}"
        h264_sed_src="^PREFIX=.*"
        h264_sed_dst="PREFIX=${h264_prefix}"
        h264_sed_dst="${h264_sed_dst//\//\\/}"
        sed -i.deleteme "s/${h264_sed_src}/${h264_sed_dst}/" "${h264_makefile}"
        rm ${h264_makefile}.deleteme
        echo "--- Run make file for ${{ matrix.arch }}"
        make OS=ios ARCH=${{ matrix.arch }} SDK_MIN=${MIN_IOS_VERSION} v=No >> "${h264_log}"  || exit
        make OS=ios ARCH=${{ matrix.arch }} SDK_MIN=${MIN_IOS_VERSION} v=No install >> "${h264_log}" || exit
        make OS=ios ARCH=${{ matrix.arch }} SDK_MIN=${MIN_IOS_VERSION} v=No clean >> "${h264_log}" || exit
        mv "${h264_makefile_bak}" "${h264_makefile}"
        popd > /dev/null
        
      shell: zsh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openssl-${{ matrix.arch }}
        path: ${{ env.OPENH264_PATH }}/builds/${{ matrix.arch }}/