name: Native iOS 
on:
  pull_request:
    types: [opened, synchronize]
  push:
    tags:
      - 'v*' 
  workflow_dispatch:
   
permissions:
  contents: write

env:
  BCG729_PATH:  ${{ github.workspace }}/lib/bcg729
  OPENH264_PATH: ${{ github.workspace }}/lib/openh264
  OPENSSL_PATH: ${{ github.workspace }}/lib/openssl
  OPUS_PATH: ${{ github.workspace }}/lib/opus
  PJSIP_PATH: ${{ github.workspace }}/lib/pjsip
  MIN_IOS_VERSION: 15.0
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  PJSIP_BUILD_OUT_PATH: ${{ github.workspace }}/outputs/pjsip-build-output
  SWIG_BUILD_OUT_PATH: ${{ github.workspace }}/outputs/swig-build-output    
  PJSIP_VERSION: 2.17
  OPENSSL_VERSION: OpenSSL_1_1_1s
  OPENH264_VERSION: v2.3.0
  OPUS_VERSION: v1.4
  BCG729_VERSION: 1.1.1
  MIN_MACOSX_VERSION: 15.0
  SDKVERSION: 26.2
  BUILD_TYPE: Release
  ROOT_DIR: ${{ github.workspace }}
  LOGS_DIR: ${{ github.workspace }}\logs
  INSTALL_DIR: ${{ github.workspace }}\install
  NUGET_ARTIFACTS: ${{ github.workspace }}/artifacts

jobs:
  bcg729-ios:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64, arm64s]
        include: 
          - lib_name: bcg729
          - arch: x86_64
            platform: iossimulator
            os_platform: iPhoneSimulator
          - arch: arm64s
            platform: iossimulator
            os_platform: iPhoneSimulator
          - arch: arm64
            platform: ios
            os_platform: iPhoneOS
    runs-on: macos-15
    name: bcg729-ios 
    permissions:
      contents: write
    steps:       
  
    - name: Cache BCG729 Built SDK
      id: cache-libs
      uses: actions/cache@v5
      with:
        path: ${{ github.workspace }}/${{ matrix.os_platform }}${{ env.MIN_IOS_VERSION }}-${{ matrix.arch }}.sdk
        key: ${{ matrix.lib_name }}-${{ env.BCG729_VERSION }}-${{ matrix.platform }}-${{ env.SDKVERSION }}-${{ matrix.arch }}
  
    - name: Clone BCG729
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ github.workspace }}/lib/
        cd ${{ github.workspace }}/lib/
        git clone --branch $BCG729_VERSION https://github.com/BelledonneCommunications/bcg729.git bcg729 
        
    - name: Setup Xcode 26.4
      uses: maxim-lobanov/setup-xcode@v1
      if: steps.cache-libs.outputs.cache-hit != 'true'
      with:
        xcode-version: '26.3'
 
    - name: Install deps
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        brew install nasm autoconf automake libtool
      shell: sh

    - name: Build bcg729 for iOS
      id: build
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        echo "Building BCG729 for iOS"
        xcode_dev_path=$(xcode-select -print-path)
        cd ${{ env.BCG729_PATH }}

        echo "-- Compiling for ${{ matrix.arch }}"

        case "${{ matrix.arch }}" in
          x86_64)
            os_platform="iPhoneSimulator"
            cmake_arch="x86_64"
            ;;
          arm64)
            os_platform="iPhoneOS"
            cmake_arch="arm64"
            ;;
          arm64s)
            os_platform="iPhoneSimulator"
            cmake_arch="arm64"
            ;;
        esac

        sdk_path="${xcode_dev_path}/Platforms/${{ matrix.os_platform }}.platform/Developer/SDKs/${{ matrix.os_platform }}.sdk"

        build_dir="${{ github.workspace }}/${{ matrix.os_platform }}${{ env.MIN_IOS_VERSION }}-${{ matrix.arch }}.sdk"
        rm -rf "$build_dir" CMakeFiles CMakeCache.txt

        mkdir -p "$build_dir"

        cmake \
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
          -DCMAKE_OSX_ARCHITECTURES=$cmake_arch \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX="$build_dir" \
          -DCMAKE_SKIP_INSTALL_RPATH=ON \
          -DCMAKE_MAKE_PROGRAM:PATH=$(which make) \
          -DCMAKE_C_COMPILER=$(which clang) \
          -DCMAKE_OSX_SYSROOT="$sdk_path" \
          .

        make || exit 1
        make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: bcg729-${{ env.BCG729_VERSION }}-${{ matrix.os_platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
        path: ${{ github.workspace }}/${{ matrix.os_platform }}${{ env.MIN_IOS_VERSION }}-${{ matrix.arch }}.sdk
        overwrite: true
   
  openh264-ios:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64, arm64s]
        include:
          - arch: arm64
            resolved_arch: arm64
            platform: iPhoneOS
          - arch: arm64s
            resolved_arch: arm64
            platform: iPhoneSimulator
          - arch: x86_64
            resolved_arch: x86_64
            platform: iPhoneSimulator
    runs-on: macos-15
    name: openh264-ios
    permissions:
      contents: write
    steps:
         
    - uses: actions/checkout@v6
      
    - name: Cache H264 Built SDK
      id: cache-libs
      uses: actions/cache@v5
      with:
        path: ${{ env. BUILT_SDK_PATH }}
        key: h264-${{ env.OPENH264_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
      env: 
        BUILT_SDK_PATH: ${{ github.workspace }}/h264-${{ env.OPENH264_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
        
    - name: Clone OpenH264
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ github.workspace }}/lib
        cd ${{ github.workspace }}/lib
        git clone --branch v2.3.0 https://github.com/cisco/openh264.git
 
    - name: Setup Xcode 26.3
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.3'
      if: steps.cache-libs.outputs.cache-hit != 'true'
        
    - name: Install deps
      run: |
        brew install nasm autoconf automake libtool 
      shell: sh
      if: steps.cache-libs.outputs.cache-hit != 'true'
          
    - name: Build OpenH264 for ${{ matrix.arch }}
      id: build
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        cd ${{ env.OPENH264_PATH }}
        h264_makefile="Makefile"
        h264_makefile_bak="Makefile.bak"

        case "${{ matrix.arch }}" in
          x86_64)
            platform="iPhoneSimulator"
            sdk="iphonesimulator"
            os="darwin"
            version_min="-mios-simulator-version-min=${{ env.MIN_IOS_VERSION }}"
            ;;
          arm64s)
            platform="iPhoneSimulator"
            sdk="iphonesimulator"
            os="darwin"
            version_min="-mios-simulator-version-min=${{ env.MIN_IOS_VERSION }}"
            ;;
          arm64)
            platform="iPhoneOS"
            sdk="iphoneos"
            os="ios"
            version_min="-miphoneos-version-min=${{ env.MIN_IOS_VERSION }}"
            ;;
        esac

        sdk_path=$(xcrun --sdk $sdk --show-sdk-path)
        developer_path=$(xcode-select -p)

        h264_prefix="${{ env.BUILT_SDK_PATH }}"
        h264_log="${h264_prefix}/build.log"
        mkdir -p "${h264_prefix}/logs"

        echo "Building OpenH264 for ${{ matrix.arch }} ($platform, OS=$os, SDK=$sdk)"

        cp "${h264_makefile}" "${h264_makefile_bak}"
        sed -i.deleteme "s|^PREFIX=.*|PREFIX=${h264_prefix}|" "${h264_makefile}"
        rm -f ${h264_makefile}.deleteme

        export CFLAGS="-arch ${{ matrix.resolved_arch }} ${version_min} -isysroot ${sdk_path}"
        export LDFLAGS="-arch ${{ matrix.resolved_arch }} ${version_min} -isysroot ${sdk_path}"
        export SYSROOT="${sdk_path}"

        make OS=${os} ARCH=${{ matrix.resolved_arch }} \
            SDK_MIN=${{ env.MIN_IOS_VERSION }} v=No >> "${h264_log}" || exit 1

        make OS=${os} ARCH=${{ matrix.resolved_arch }} \
            SDK_MIN=${{ env.MIN_IOS_VERSION }} v=No install >> "${h264_log}" || exit 1

        make OS=${os} ARCH=${{ matrix.resolved_arch }} \
            SDK_MIN=${{ env.MIN_IOS_VERSION }} v=No clean >> "${h264_log}" || exit 1

        mv "${h264_makefile_bak}" "${h264_makefile}"
 
      shell: bash
      env: 
        BUILT_SDK_PATH: ${{ github.workspace }}/h264-${{ env.OPENH264_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: h264-${{ env.OPENH264_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
        path: ${{ github.workspace }}/h264-${{ env.OPENH264_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
        overwrite: true

  openssl-ios:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64, arm64s]
        include:
          - arch: x86_64
            resolved_arch: x86_64
            sdk: iphonesimulator
            platform: iPhoneSimulator
            target: ios-sim-cross-x86_64
          - arch: arm64
            resolved_arch: arm64
            sdk: iphoneos
            platform: iPhoneOS
            target: ios-cross-arm64
          - arch: arm64s
            resolved_arch: arm64
            sdk: iphonesimulator
            platform: iPhoneSimulator
            target: ios-sim-cross-arm64
    runs-on: macos-15
    name: openssl-ios 
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6 
    
    - name: Cache SSL Built SDK
      id: cache-libs
      uses: actions/cache@v5
      with:
        path: ${{ env.OPENSSL_PATH }}/bin/${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.resolved_arch }}.sdk
        key: ssl-${{ env.OPENSSL_VERSION }}-${{ matrix.platform }}

    - name: Clone OpenSSL
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ github.workspace }}/lib/
        cd ${{ github.workspace }}/lib/
        git clone --branch $OPENSSL_VERSION https://github.com/openssl/openssl.git --recursive      

    - name: Setup Xcode 26.3
      uses: maxim-lobanov/setup-xcode@v1
      if: steps.cache-libs.outputs.cache-hit != 'true'
      with:
        xcode-version: '26.3'
 
    - name: Install deps
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        brew install nasm autoconf automake libtool 
      shell: sh
        
    - name: Build OpenSSL
      if: steps.cache-libs.outputs.cache-hit != 'true'
      id: build
      run: |
        INCLUDE_DIR=""
        OPENSSLCONF_ALL=()
        LIBSSL_IOS=()
        LIBSSL_IOSSIM=()
        LIBCRYPTO_IOS=()
        LIBCRYPTO_IOSSIM=()
        export OPENSSL_LOCAL_CONFIG_DIR=${{ github.workspace }}/res/ssl/config
        SDKVERSION=$(xcrun -sdk ${{ matrix.sdk }} --show-sdk-version)
        export SDKVERSION
        export IOS_MIN_SDK_VERSION=15.0
        export CONFIG_DISABLE_BITCODE=true 
        export CONFIG_OPTIONS="no-dso no-shared no-engine no-tests no-unit-test no-ssl3 no-comp enable-ec_nistp_64_gcc_128"
        cd ${{ env.OPENSSL_PATH }}
        
        chmod u+x ./Configure
        
        TARGET=${{ matrix.target }}
        PLATFORM=${{ matrix.platform }}
        ARCH=${{ matrix.resolved_arch }}
        # Cross compile references, see Configurations/10-main.conf
        export CROSS_COMPILE="${{ env.DEVELOPER }}/Toolchains/XcodeDefault.xctoolchain/usr/bin/"
        export CROSS_TOP="${{ env.DEVELOPER }}/Platforms/${{ matrix.platform }}.platform/Developer"
        export CROSS_SDK="${{ matrix.platform }}${{ env.SDKVERSION }}.sdk"

        # Prepare TARGETDIR  
        TARGETDIR="${{ env.OPENSSL_PATH }}/bin/${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.resolved_arch }}.sdk"
        echo "artifact=${TARGETDIR}" >> "$GITHUB_OUTPUT"
        mkdir -p "${TARGETDIR}"
        ## Determine config options
        # Add build target, --prefix and prevent async (references to getcontext(),
        # setcontext() and makecontext() result in App Store rejections) and creation
        # of shared libraries (default since 1.1.0)
        LOCAL_CONFIG_OPTIONS="${TARGET} --prefix=${TARGETDIR} ${CONFIG_OPTIONS} no-async no-shared"

        # Only relevant for 64 bit builds
        # if [[ "${CONFIG_ENABLE_EC_NISTP_64_GCC_128}" == "true" && "${{ matrix.resolved_arch }}" == *64  ]]; then
        #     LOCAL_CONFIG_OPTIONS="${LOCAL_CONFIG_OPTIONS} enable-ec_nistp_64_gcc_128"
        # fi

        export CFLAGS="-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK} -mios-version-min=${IOS_MIN_SDK_VERSION}"
        export LDFLAGS="-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK}"

        # Run Configure
        ./Configure ${LOCAL_CONFIG_OPTIONS} no-tests 

        # Run make
        echo "  Make (using ${{ env.BUILD_THREADS }} thread(s))..." 
        make build_libs -j "${{ env.BUILD_THREADS }}"  
 
        # Run make install
        set -e 
        make install_dev  

        # Remove source dir, add references to library files to relevant arrays
        # Keep reference to first build target for include file
        if [[ "${{ matrix.platform }}" == iPhoneOS ]]; then
            LIBSSL_IOS+=("${TARGETDIR}/lib/libssl.a")
            LIBCRYPTO_IOS+=("${TARGETDIR}/lib/libcrypto.a")
            OPENSSLCONF_SUFFIX="ios_${{matrix.arch}}"
        elif [[ "${PLATFORM}" == iPhoneSimulator ]]; then
            LIBSSL_IOSSIM+=("${TARGETDIR}/lib/libssl.a")
            LIBCRYPTO_IOSSIM+=("${TARGETDIR}/lib/libcrypto.a")
            OPENSSLCONF_SUFFIX="ios_${{ matrix.arch }}"
        fi
      shell: bash
      env:
        DEVELOPER: $(xcode-select -print-path)
        BUILD_THREADS: $(sysctl -n hw.ncpu)  

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: openssl-${{ matrix.arch }}
        path: ${{ env.OPENSSL_PATH }}/bin/${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.resolved_arch }}.sdk
        overwrite: true 

  opus-ios:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64, arm64s]
        include:
          - arch: arm64
            resolved_arch: arm64
            platform: iPhoneOS
          - arch: arm64s
            resolved_arch: arm64
            platform: iPhoneSimulator
          - arch: x86_64
            resolved_arch: x86_64
            platform: iPhoneSimulator
    runs-on: macos-15
    name: opus-ios 
    permissions:
      contents: write
    steps:
     
    - name: Cache opus Built SDK
      id: cache-libs
      uses: actions/cache@v5
      with:
        path: ${{ github.workspace }}/opus/build/${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.resolved_arch }}.sdk
        key: opus-${{ env.OPUS_VERSION }}-${{ matrix.platform }}-${{ env.SDKVERSION }}-${{ matrix.arch }}

    - name: Clone Opus
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ github.workspace }}/lib
        cd ${{ github.workspace }}/lib
        git clone --branch v1.4 https://github.com/xiph/opus.git opus

    - name: Setup Xcode 26.3
      if: steps.cache-libs.outputs.cache-hit != 'true'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.3'
 
    - name: Install deps
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        brew install nasm autoconf automake libtool 
      shell: sh
         
    - name: Build opus
      id: build
      if: steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        opus_version="1.4"
        opus_opt_cflags="-O3 -ffast-math -flto -g"
        opus_opt_ldflags="-flto"
        DEVELOPER=$(xcode-select -print-path)
        SDKVERSION=$(xcrun -sdk ${{ matrix.arch == 'arm64' && 'iphoneos' || 'iphonesimulator' }} --show-sdk-version)
        PLATFORM=${{ matrix.platform }}
        TARGETDIR="${{ github.workspace }}/opus/build/${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.resolved_arch }}.sdk"

        mkdir -p "${TARGETDIR}/include"
        mkdir -p "${TARGETDIR}/lib"

        echo "artifact=${TARGETDIR}" >> "$GITHUB_OUTPUT"
        echo "-- Building Opus for ${{ matrix.arch }} on ${PLATFORM}"

        cd "${{ env.OPUS_PATH }}"

        ./autogen.sh
 
        if [[ "${{ matrix.arch }}" == "x86_64" ]]; then
          HOST="x86_64-apple-darwin" 
          opus_opt_cflags="-O3 -ffast-math -flto -g -Wno-cast-align"
        else
          HOST="arm-apple-darwin" 
          opus_opt_cflags="-O3 -ffast-math -flto -g"
        fi
        version_min=$([[ "${{ matrix.arch }}" == "arm64" ]] && echo "-miphoneos-version-min=${{ env.MIN_IOS_VERSION }}" || echo "-mios-simulator-version-min=${{ env.MIN_IOS_VERSION }}")
        ARCH="${{ matrix.resolved_arch }}"
        
        ./configure \
          --enable-float-approx \
          --disable-shared \
          --enable-static \
          --with-pic \
          --disable-extra-programs \
          --disable-doc \
          --host=${HOST} \
          --prefix="${TARGETDIR}" \
          LDFLAGS="${opus_opt_ldflags} -fPIE ${version_min} -L${TARGETDIR}/lib" \
          CFLAGS="${opus_opt_cflags} -arch ${ARCH} -fPIE ${version_min} -I${TARGETDIR}/include -isysroot ${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer/SDKs/${PLATFORM}${SDKVERSION}.sdk"

        make -j${{ env.BUILD_THREADS }}
        make install 
      shell: sh
      env:
        CONFIG_DISABLE_BITCODE: true
        DEVELOPER: $(xcode-select -print-path)
        IOS_SDKVERSION: $(xcrun -sdk iphoneos --show-sdk-version)
        BUILD_THREADS: $(sysctl -n hw.ncpu)

    - name: Patch Opus .pc for arm64s
      if: matrix.arch == 'arm64s' && steps.cache-libs.outputs.cache-hit != 'true'
      run: |
        opus_build_dir=$(find "${{ github.workspace }}/opus/build/" -type d -name "iPhoneSimulator*-arm64.sdk" | head -n 1)
        pc_file=$(find "$opus_build_dir/lib/pkgconfig" -name 'opus.pc' | head -n 1)

        if [ -f "$pc_file" ]; then
          install_prefix="${{ github.workspace }}/libs/opus"
          sed -i'' -e "s|^prefix=.*|prefix=${install_prefix}|" "$pc_file"
          sed -i'' -e "s|^exec_prefix=.*|exec_prefix=${install_prefix}|" "$pc_file"
          sed -i'' -e "s|^libdir=.*|libdir=${install_prefix}/lib|" "$pc_file"
          sed -i'' -e "s|^includedir=.*|includedir=${install_prefix}/include|" "$pc_file"
          sed -i'' -e "s|^Cflags=.*|Cflags=-I${install_prefix}/include/opus|" "$pc_file"
          echo "Patched Opus pkg-config file for PJSIP:"
          cat "$pc_file"
        else
          echo "Opus .pc file not found in $opus_build_dir"
          exit 1
        fi
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: opus-${{ matrix.arch }}
        path: ${{ github.workspace }}/opus/build/${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.resolved_arch }}.sdk
        overwrite: true

  pjsip-ios:
    strategy:
      matrix:
        arch: [x86_64, arm64, arm64s]
        include:
        - arch: arm64
          resolved_arch: arm64
          sdk: iphoneos
          platform: iPhoneOS
        - arch: arm64s
          resolved_arch: arm64
          sdk: iphonesimulator
          platform: iPhoneSimulator
        - arch: x86_64
          resolved_arch: x86_64
          sdk: iphonesimulator
          platform: iPhoneSimulator
      fail-fast: false
    runs-on: macos-15
    needs: [bcg729-ios, openh264-ios, openssl-ios, opus-ios]
    name: pjsip - ios
    permissions:
      contents: write
    steps:
      
      - uses: actions/checkout@v6
      
      - name: Cache pjsip Built SDK
        uses: actions/cache@v5
        id: cache-libs
        with:
          path: ${{ github.workspace }}/pjsip-${{matrix.arch}}
          key: pjsip-${{ env.PJSIP_VERSION }}${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}

      - name: Clone PJSIP
        if: steps.cache-libs.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ github.workspace }}/lib
          cd ${{ github.workspace }}/lib
          git clone --branch $PJSIP_VERSION https://github.com/pjsip/pjproject.git pjsip
      
      - uses: actions/download-artifact@v8
        if: steps.cache-libs.outputs.cache-hit != 'true'
        with:
          name: openssl-${{ matrix.arch }}
          path: ${{ github.workspace }}/libs/ssl/
      
      - uses: actions/download-artifact@v8
        if: steps.cache-libs.outputs.cache-hit != 'true'
        with:
          name: h264-${{ env.OPENH264_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
          path: ${{ github.workspace }}/libs/h264/
      
      - uses: actions/download-artifact@v8
        if: steps.cache-libs.outputs.cache-hit != 'true'
        with:
          name: opus-${{ matrix.arch }}
          path: ${{ github.workspace }}/libs/opus/
      
      - uses: actions/download-artifact@v8
        if: steps.cache-libs.outputs.cache-hit != 'true'
        with:
          name: bcg729-${{ env.BCG729_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
          path: ${{ github.workspace }}/libs/bcg729/

      - name: Validate Deps
        if: steps.cache-libs.outputs.cache-hit != 'true'
        working-directory: libs
        shell: pwsh
        run: ls -R .
          
      - name: Install dependencies
        if: steps.cache-libs.outputs.cache-hit != 'true'
        run: |
          brew install automake autoconf libtool pkg-config swig llvm

      - name: Setup Xcode 26.3
        if: steps.cache-libs.outputs.cache-hit != 'true'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.3'
 
      - name: Build pjsip
        id: build-pj-ios
        if: steps.cache-libs.outputs.cache-hit != 'true'
        run: |
          cp -f ${{ github.workspace }}/res/pj/config_site.h ${{ env.PJSIP_PATH }}/pjlib/include/pj/config_site.h
          mkdir -p ~/pjsip_build/bundle/${{ matrix.arch }}
          cp -r ${{ env.PJSIP_PATH }} ~/pjsip_build/bundle/${{ matrix.arch }}
          cd ~/pjsip_build/bundle/${{ matrix.arch }}/pjsip
          export SDKVERSION=$(xcrun -sdk ${{ matrix.sdk }} --show-sdk-version)
          export IPHONESDK="${{ matrix.platform}}${SDKVERSION}.sdk" 
          export DEVPATH="$(xcode-select -p)/Platforms/${{ matrix.platform }}.platform/Developer"
          export SDKROOT="${DEVPATH}/SDKs/${{ matrix.platform }}.sdk"
          export SDKPATH="${DEVPATH}/SDKs/${IPHONESDK}" 

          if [ "${{ matrix.arch }}" == "arm64" ]; then
            export CFLAGS=" -arch ${{ matrix.resolved_arch }} ${CFLAGS}"
            export LDFLAGS="-arch ${{ matrix.resolved_arch }} ${LDFLAGS}"
            export MIN_IOS=-miphoneos-version-min=${{ env.MIN_IOS_VERSION }}
          else
            export CFLAGS=" -arch ${{ matrix.resolved_arch }} ${CFLAGS} -O2 -m64"
            export LDFLAGS="-arch ${{ matrix.resolved_arch }} ${LDFLAGS} -O2 -m64"
            export MIN_IOS="-mios-simulator-version-min=${{ env.MIN_IOS_VERSION }}"
          fi
           
          ARCH="-arch ${{ matrix.resolved_arch }}" ./configure-iphone \
              --with-bcg729=${{ github.workspace }}/libs/bcg729 \
              --with-ssl=${{ github.workspace }}/libs/ssl \
              --with-opus=${{ github.workspace }}/libs/opus \
              --with-openh264=${{ github.workspace }}/libs/h264
          echo "FLAGS AFTER CONFIGURE:"
          echo ""
          echo "CFLAGS=${CFLAGS}"
          echo "LDFLAGS=${LDFLAGS}"
          # Deduplicar CFLAGS
          export CFLAGS=$(echo "$CFLAGS" | tr ' ' '\n' | awk '!seen[$0]++' | tr '\n' ' ')
          # Deduplicar LDFLAGS
          export LDFLAGS=$(echo "$LDFLAGS" | tr ' ' '\n' | awk '!seen[$0]++' | tr '\n' ' ')
          echo "FLAGS AFTER DEDUPLICATE:"
          echo ""
          echo "CFLAGS=${CFLAGS}"
          echo "LDFLAGS=${LDFLAGS}"
          
          make dep
          make

          cd ./pjsip-apps/src/swig/csharp/pjsua2maui
          cp -v ${{ github.workspace }}/res/pj/pjsua2maui/Makefile .

          echo "Starting make iOS"
          make
          echo "Starting copy"
          
          mkdir -p ${{ github.workspace }}/merge
          mkdir -p ${{ github.workspace }}/pjsip-${{matrix.arch}}/lib
          mkdir -p ${{ github.workspace }}/pjsip-${{matrix.arch}}/cs
          cp -v -f ${{ github.workspace }}/libs/ssl/lib/*.a ${{ github.workspace }}/merge
          cp -v -f ${{ github.workspace }}/libs/opus/lib/*.a ${{ github.workspace }}/merge
          cp -v -f ${{ github.workspace }}/libs/bcg729/lib/*.a ${{ github.workspace }}/merge
          cp -v -f ${{ github.workspace }}/libs/h264/lib/*.a ${{ github.workspace }}/merge
          cp -v -f ./pjsua2maui/Platforms/iOS/lib/${{ matrix.resolved_arch }}/*.a ${{ github.workspace }}/merge
          libtool -static -o ${{ github.workspace }}/pjsip-${{matrix.arch}}/lib/libpjsua2.a ${{ github.workspace }}/merge/*.a
          cp -v -f ./pjsua2maui/Platforms/iOS/pjsua2/*.cs ${{ github.workspace }}/pjsip-${{matrix.arch}}/cs
          
        env:
          BUILD_THREADS: $(sysctl -n hw.ncpu)

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: pjsip-${{ env.PJSIP_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
          path: ${{ github.workspace }}/pjsip-${{matrix.arch}}
          overwrite: true
       